-- Production seed: intentionally empty.
--
-- The live environment starts with NO fleet and NO parcels. (This file once
-- held a demo dataset — 3 drivers / 3 routes / 8 parcels / 4 sites — which was
-- removed when the app went live.) Parcels are created through the dispatcher's
-- Jobs → "Import a manifest" flow; drivers/routes are provisioned per the shape
-- below, then a driver's profile is pointed at their driver id.
--
-- Add a real fleet (driver id is free text; routes.delivery_areas /
-- collection_areas drive auto-allocation by UK postcode-area prefix, e.g. 'SW',
-- 'SE', 'CR' — an open set of ~120 UK outward prefixes, no fixed enum):
--
--   insert into drivers (id, name) values ('drv_acme', 'Driver Name');
--
--   insert into routes (name, driver_id, delivery_areas, collection_areas)
--     values ('South London run', 'drv_acme', array['SW','SE','CR'], array['CR']);
--
--   -- map a signed-in driver account to that driver:
--   update profiles set driver_id = 'drv_acme'
--    where id = (select id from auth.users where email = 'driver@example.com');
--
-- Auth accounts themselves are created out-of-band (Supabase admin API /
-- scripts/seed-auth.mjs), never from plain SQL seed.
